### ISSUE TITLE
This example fails to run complaining that System.ArgumentException: ''authority' should be in URI format.  Arg_ParamName_Name'

### ISSUE THREAD

**Issue by duncangroenewald** [Azure-Samples/azure-iot-central-samples-csharp#10]
Fails on line 19 in Program.cs

**Comment by duncangroenewald** [comment]
Unhandled exception. System.ArgumentException: 'authority' should be in URI format.  (Parameter 'authority')
   at Microsoft.Identity.Client.AuthorityInfo.ValidateAndCreateAuthorityUri(String authority, Nullable`1 authorityType)
   at Microsoft.Identity.Client.AuthorityInfo.FromAuthorityUri(String authorityUri, Boolean validateAuthority)
   at Microsoft.Identity.Client.Instance.Authority.CreateAuthority(String authority, Boolean validateAuthority)
   at Microsoft.Identity.Client.AbstractApplicationBuilder`1.WithAuthority(String authorityUri, Boolean validateAuthority)
   at Examples.Program.Main(String[] args) in C:\Users\xxxxx\Development\azure-iot-central-samples-csharp\samples\Examples\Program.cs:line 19
